# Chapter8

In [1]:
x <- 10

In [2]:
x

[1] 10

In [3]:
y <- c(1,2,4)

In [4]:
y

[1] 1 2 4

In [5]:
veca <- c(1,2,3,4,5)

In [6]:
veca

[1] 1 2 3 4 5

In [7]:
veca2 <- 1:5

In [8]:
veca2

[1] 1 2 3 4 5

In [9]:
veca3 <- 5:10

In [10]:
veca3

[1]  5  6  7  8  9 10

In [11]:
veca4 <- 10:1

In [12]:
veca4

[1] 10  9  8  7  6  5  4  3  2  1

In [13]:
veca5 <- -5:5

In [14]:
veca5

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [15]:
veca6 <- seq (1,5 ,1)

In [16]:
veca6

[1] 1 2 3 4 5

In [19]:
vecb <- seq(2,10,2)

In [20]:
vecb

[1]  2  4  6  8 10

In [21]:
vecc <- rep(1,8)

In [22]:
vecc

[1] 1 1 1 1 1 1 1 1

In [23]:
veca + vecb

[1]  3  6  9 12 15

In [24]:
veca - vecb

[1] -1 -2 -3 -4 -5

In [26]:
veca * vecb

[1]  2  8 18 32 50

In [27]:
veca/vecb

[1] 0.5 0.5 0.5 0.5 0.5

In [28]:
veca%*%vecb

[,1]
[1,] 110

In [29]:
veca * 5

[1]  5 10 15 20 25

In [30]:
vecd <- c(2,4)

In [31]:
veca + vecd

Warning message in veca + vecd:
“ 長いオブジェクトの長さが短いオブジェクトの長さの倍数になっていません ”

[1] 3 6 5 8 7

In [32]:
veca * vecd

Warning message in veca * vecd:
“ 長いオブジェクトの長さが短いオブジェクトの長さの倍数になっていません ”

[1]  2  8  6 16 10

In [33]:
vece <- 10:20

In [34]:
vece

[1] 10 11 12 13 14 15 16 17 18 19 20

In [36]:
vece[2]

[1] 11

In [38]:
vece[3:7]

[1] 12 13 14 15 16

In [39]:
vecf <- vece[c(2,4,6,8)]

In [40]:
vecf

[1] 11 13 15 17

In [41]:
vecg <- vece[c(10,1,8,6)]

In [42]:
vecg

[1] 19 10 17 15

In [43]:
matrix(1:12,nrow=3,ncol=4)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [44]:
matrix(1:12,3,4)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [45]:
matrix(1:12,3,4, byrow = TRUE)

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [46]:
cbind(veca, vecb)

veca vecb
[1,] 1     2  
[2,] 2     4  
[3,] 3     6  
[4,] 4     8  
[5,] 5    10

In [47]:
rbind(veca, vecb)

[,1] [,2] [,3] [,4] [,5]
veca 1    2    3    4     5  
vecb 2    4    6    8    10

In [48]:
mata <- matrix(1:6,nrow=2,ncol=3)

In [51]:
rownames(mata) <- c("row1","row2")

In [52]:
colnames(mata) <- c("col1","col2","col3")

In [53]:
mata

col1 col2 col3
row1 1    3    5   
row2 2    4    6

In [54]:
matb <- matrix(3:8,nrow=2,ncol=3)

In [55]:
mata + matb

col1 col2 col3
row1 4     8   12  
row2 6    10   14

In [56]:
mata - matb

col1 col2 col3
row1 -2   -2   -2  
row2 -2   -2   -2

In [57]:
mata*matb

col1 col2 col3
row1 3    15   35  
row2 8    24   48

In [58]:
mata/matb

col1      col2      col3     
row1 0.3333333 0.6000000 0.7142857
row2 0.5000000 0.6666667 0.7500000

In [59]:
matt<- t(matb)

In [60]:
matt

[,1] [,2]
[1,] 3    4   
[2,] 5    6   
[3,] 7    8

In [61]:
t(matt)

[,1] [,2] [,3]
[1,] 3    5    7   
[2,] 4    6    8

In [62]:
matt%*%mata

col1 col2 col3
[1,] 11   25   39  
[2,] 17   39   61  
[3,] 23   53   83

In [63]:
matc <- matrix(1:9,nrow=3,ncol=3)

In [64]:
matc

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [65]:
diag(c(1,2,3))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [66]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [68]:
matc%*%diag(3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [69]:
matd <- matrix(1:25,nrow=5,ncol=5)

In [70]:
matd

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [72]:
matd[,2]

[1]  6  7  8  9 10

In [73]:
matd[2,]

[1]  2  7 12 17 22

In [75]:
matd[,c(1,3)]

[,1] [,2]
[1,] 1    11  
[2,] 2    12  
[3,] 3    13  
[4,] 4    14  
[5,] 5    15

In [76]:
matd[c(2,4), ]

[,1] [,2] [,3] [,4] [,5]
[1,] 2    7    12   17   22  
[2,] 4    9    14   19   24

In [77]:
matd[2,4]

[1] 17